// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace PlayerPerformance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayerPerformance.Infrastructure.Persistence.AppDbContext))]
    [Migration("20260711120000_AddPlayersBackendFoundation")]
    partial class AddPlayersBackendFoundation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The authoritative current model is maintained in AppDbContextModelSnapshot.
        }
    }
}
