using FluentValidation;
using PlayerPerformance.Domain.Common.Errors;
using PlayerPerformance.Domain.Common.Results;
using PlayerPerformance.Domain.Matches;

namespace PlayerPerformance.Application.Matches;

public sealed record CreateMatchRequest(Guid SeasonId, Guid CompetitionId, Guid TeamId, Guid OpponentId, Guid? VenueId, DateTime KickoffAtUtc, string? Round, MatchLocationType LocationType);
public sealed record UpdateMatchRequest(Guid SeasonId, Guid CompetitionId, Guid OpponentId, Guid? VenueId, DateTime KickoffAtUtc, string? Round, MatchLocationType LocationType, MatchStatus Status, int? TeamScore, int? OpponentScore);
public sealed record MatchListQuery(Guid? SeasonId, Guid? TeamId, Guid? CompetitionId, Guid? OpponentId, MatchStatus? Status, DateTime? DateFrom, DateTime? DateTo, bool IncludeArchived = false, int Page = 1, int PageSize = 25);
public sealed record MatchReferenceResponse(Guid Id, string Name);
public sealed record MatchResponse(Guid Id, MatchReferenceResponse Season, MatchReferenceResponse Competition, MatchReferenceResponse Team, MatchReferenceResponse Opponent, MatchReferenceResponse? Venue, DateTime KickoffAtUtc, string? Round, MatchLocationType LocationType, MatchStatus Status, int? TeamScore, int? OpponentScore, bool IsArchived, DateTime CreatedAtUtc, DateTime UpdatedAtUtc);
public sealed record PagedMatchListResponse(IReadOnlyList<MatchResponse> Items, int Page, int PageSize, int TotalCount, int TotalPages);
public sealed class CreateMatchRequestValidator : AbstractValidator<CreateMatchRequest> { public CreateMatchRequestValidator() { RuleFor(x => x.SeasonId).NotEmpty(); RuleFor(x => x.CompetitionId).NotEmpty(); RuleFor(x => x.TeamId).NotEmpty(); RuleFor(x => x.OpponentId).NotEmpty(); RuleFor(x => x.KickoffAtUtc).Must(x => x != default && x.Kind == DateTimeKind.Utc); RuleFor(x => x.Round).MaximumLength(80); RuleFor(x => x.LocationType).IsInEnum(); } }
public sealed class UpdateMatchRequestValidator : AbstractValidator<UpdateMatchRequest> { public UpdateMatchRequestValidator() { RuleFor(x => x.SeasonId).NotEmpty(); RuleFor(x => x.CompetitionId).NotEmpty(); RuleFor(x => x.OpponentId).NotEmpty(); RuleFor(x => x.KickoffAtUtc).Must(x => x != default && x.Kind == DateTimeKind.Utc); RuleFor(x => x.Round).MaximumLength(80); RuleFor(x => x.LocationType).IsInEnum(); RuleFor(x => x.Status).IsInEnum(); RuleFor(x => x).Must(x => x.TeamScore.HasValue == x.OpponentScore.HasValue && x.TeamScore is not < 0 && x.OpponentScore is not < 0 && (x.Status == MatchStatus.PLAYED) == x.TeamScore.HasValue); } }
public sealed class MatchListQueryValidator : AbstractValidator<MatchListQuery> { public MatchListQueryValidator() { RuleFor(x => x.Page).InclusiveBetween(1, 100000); RuleFor(x => x.PageSize).InclusiveBetween(1, 100); RuleFor(x => x.Status).IsInEnum().When(x => x.Status.HasValue); RuleFor(x => x).Must(x => !x.DateFrom.HasValue || !x.DateTo.HasValue || x.DateFrom <= x.DateTo); } }
public interface IMatchesService { Task<Result<PagedMatchListResponse>> ListAsync(MatchListQuery query, CancellationToken ct); Task<MatchResponse?> GetAsync(Guid id, CancellationToken ct); Task<Result<MatchResponse>> CreateAsync(CreateMatchRequest request, CancellationToken ct); Task<Result<MatchResponse>> UpdateAsync(Guid id, UpdateMatchRequest request, CancellationToken ct); Task<Result<MatchResponse>> ArchiveAsync(Guid id, CancellationToken ct); Task<Result<MatchResponse>> RestoreAsync(Guid id, CancellationToken ct); }
public interface IMatchesRepository { Task<Match?> GetAsync(Guid id, CancellationToken ct); Task<MatchReadModel?> GetReadAsync(Guid id, IReadOnlyCollection<Guid>? teamScope, CancellationToken ct); Task<PagedMatchReadModel> ListAsync(MatchListQuery query, IReadOnlyCollection<Guid>? teamScope, CancellationToken ct); Task<bool> ExactDuplicateExistsAsync(Guid teamId, Guid opponentId, DateTime kickoffAtUtc, CancellationToken ct); Task<MatchReferences?> GetActiveReferencesAsync(Guid seasonId, Guid competitionId, Guid teamId, Guid opponentId, Guid? venueId, CancellationToken ct); void Add(Match match); Task SaveChangesAsync(CancellationToken ct); }
public sealed record MatchReferences(DateOnly SeasonStartDate, DateOnly SeasonEndDate);
public sealed record MatchReadModel(Match Match, string SeasonName, string CompetitionName, string TeamName, string OpponentName, string? VenueName);
public sealed record PagedMatchReadModel(IReadOnlyList<MatchReadModel> Items, int TotalCount);
internal static class MatchErrors { public static readonly Error NotFound = new("not_found", "The requested match was not found."); public static readonly Error Forbidden = new("forbidden", "You do not have access to this match."); public static readonly Error Validation = new("validation_failed", "One or more fields are invalid."); public static readonly Error References = new("invalid_references", "One or more selected match references are invalid or archived."); public static readonly Error Duplicate = new("duplicate_match", "An identical active match already exists."); public static readonly Error Conflict = new("match_conflict", "The requested match change is not allowed."); }
